import Head from "next/head";
import "./globals.css";
import type { Metadata } from "next";
import { ChildrenProps } from "@/types/type";

export const metadata: Metadata = {
  title: "Todo App",
  description: "Generated by Todo App",
};

export default function RootLayout({ children }:ChildrenProps) {
  return (
    <html>
      <body className="bg-gray-200">{children}</body>
    </html>
  );
}
